### ISSUE TITLE
Adding a prefix with a space in front of the actual prefix breaks the bot

### ISSUE THREAD

**Issue by XorogVEVO** [kikkia/Vinny#262]
## Feature Request or Issue?
Issue

## Overview
When adding a space in front of the prefix while already having the same prefix makes vinny respond to no prefix at all.

How to recreate:

Add a prefix (e.g.) a comma

`@Vinny addprefix ,`

Add the same prefix with an extra space

`@Vinny addprefix  ,`

(for some reason github removes the second space between addprefix and the comma, should be there but isn't)

Remove the first added prefix

`@Vinny removeprefix ,`

Theres no an empty prefix, which makes the bot respond to no prefix at all.

![Screenshot of Discord](https://cdn.discordapp.com/attachments/818096299911544906/820388771177955338/Screenshot_8.png)

This might not be a big deal but i thought i should report it anyways.

**Comment by kikkia** [comment]
Hey, thanks a lot for bringing this up, I'll work on getting a fix out
